import type { Choice, ChoiceEffects, Scenario, ScenarioCategory, Rarity } from "./types";
import { describeEffects } from "./describe";

/**
 * Scenario bank for "55 Seconds".
 *
 * Every scenario is a fictional entrepreneurship situation. Choices reward
 * smart, legitimate business decisions. There is intentionally NO option that
 * involves fraud, fake documents, deceiving a bank, identity theft or any
 * illegal behaviour — the "risk" axis only models commercial over-exposure
 * (over-promising, cashflow strain, reputation), never wrongdoing.
 */

const E = (e: Partial<ChoiceEffects>): ChoiceEffects => ({
  balanceDelta: e.balanceDelta ?? 0,
  flowDelta: e.flowDelta ?? 0,
  transactionsDelta: e.transactionsDelta ?? 0,
  confidenceDelta: e.confidenceDelta ?? 0,
  riskDelta: e.riskDelta ?? 0,
  momentumDelta: e.momentumDelta ?? 0,
  multiplierDelta: e.multiplierDelta,
});

const ch = (
  id: string,
  label: string,
  tone: Choice["tone"],
  effects: ChoiceEffects,
): Choice => ({
  id,
  label,
  tone,
  effects,
  effectDescription: describeEffects(effects),
});

let counter = 0;
const sc = (
  category: ScenarioCategory,
  icon: string,
  rarity: Rarity,
  title: string,
  description: string,
  projectAmount: number,
  choices: Choice[],
): Scenario => ({
  id: `s${++counter}`,
  category,
  icon,
  rarity,
  title,
  description,
  projectAmount,
  choices,
});

export const SCENARIOS: Scenario[] = [
  sc(
    "urgence",
    "UtensilsCrossed",
    "common",
    "Restaurateur pressé",
    "Un restaurateur veut une landing page livrée en 48h. Il propose un acompte immédiat.",
    2800,
    [
      ch("a", "Accepter l'acompte", "safe", E({ flowDelta: 1200, balanceDelta: 600, transactionsDelta: 6, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Négocier une offre premium", "premium", E({ flowDelta: 2500, balanceDelta: 800, transactionsDelta: 7, confidenceDelta: 4, riskDelta: 6, momentumDelta: 2 })),
      ch("c", "Refuser, délai trop court", "refuse", E({ confidenceDelta: 2, momentumDelta: -2 })),
    ],
  ),
  sc(
    "freelance",
    "Dumbbell",
    "common",
    "Coach sportif",
    "Un coach sportif veut remplir son planning de la semaine.",
    1500,
    [
      ch("a", "Pack réservation simple", "safe", E({ flowDelta: 900, balanceDelta: 400, transactionsDelta: 7, confidenceDelta: 7, momentumDelta: 1 })),
      ch("b", "Tunnel + relances auto", "premium", E({ flowDelta: 1900, balanceDelta: 650, transactionsDelta: 9, confidenceDelta: 5, riskDelta: 4, momentumDelta: 2 })),
      ch("c", "Trop petit, passer", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "immobilier",
    "Home",
    "rare",
    "Agent immobilier",
    "Un agent immobilier veut un flux régulier de leads qualifiés.",
    3600,
    [
      ch("a", "Page de capture propre", "safe", E({ flowDelta: 1400, balanceDelta: 700, transactionsDelta: 6, confidenceDelta: 9, momentumDelta: 2 })),
      ch("b", "Système leads + scoring", "premium", E({ flowDelta: 3000, balanceDelta: 950, transactionsDelta: 8, confidenceDelta: 3, riskDelta: 7, momentumDelta: 2 })),
      ch("c", "Refuser le volume", "refuse", E({ confidenceDelta: 3, momentumDelta: -2 })),
    ],
  ),
  sc(
    "commerce",
    "Scissors",
    "common",
    "Salon de coiffure",
    "Un salon veut automatiser ses réservations et réduire les no-shows.",
    1900,
    [
      ch("a", "Agenda en ligne", "safe", E({ flowDelta: 1000, balanceDelta: 450, transactionsDelta: 8, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Réservation + rappels SMS", "premium", E({ flowDelta: 2100, balanceDelta: 700, transactionsDelta: 10, confidenceDelta: 4, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Décliner", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "freelance",
    "GraduationCap",
    "common",
    "Formateur indépendant",
    "Un formateur veut lancer un mini-programme en ligne ce week-end.",
    2200,
    [
      ch("a", "Page de vente claire", "safe", E({ flowDelta: 1300, balanceDelta: 550, transactionsDelta: 7, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Offre premium + bonus", "premium", E({ flowDelta: 2600, balanceDelta: 850, transactionsDelta: 8, confidenceDelta: 3, riskDelta: 6, momentumDelta: 2 })),
      ch("c", "Reporter le lancement", "refuse", E({ confidenceDelta: 2, momentumDelta: -3 })),
    ],
  ),
  sc(
    "reputation",
    "HeartHandshake",
    "rare",
    "Association de quartier",
    "Une association veut une page de dons transparente pour son projet.",
    1200,
    [
      ch("a", "Page de dons soignée", "safe", E({ flowDelta: 800, balanceDelta: 350, transactionsDelta: 9, confidenceDelta: 12, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Page + suivi d'impact", "premium", E({ flowDelta: 1500, balanceDelta: 500, transactionsDelta: 10, confidenceDelta: 8, momentumDelta: 2 })),
      ch("c", "Pas le bon moment", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "commerce",
    "MessageCircle",
    "common",
    "Commerçant local",
    "Un commerçant veut un tunnel de commande simple via WhatsApp.",
    1700,
    [
      ch("a", "Catalogue + commande", "safe", E({ flowDelta: 1100, balanceDelta: 500, transactionsDelta: 8, confidenceDelta: 7, momentumDelta: 2 })),
      ch("b", "Tunnel + paiement intégré", "premium", E({ flowDelta: 2200, balanceDelta: 750, transactionsDelta: 11, confidenceDelta: 4, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Refuser", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "ia",
    "Cpu",
    "epic",
    "PME en transition",
    "Une PME veut un audit d'automatisation pour gagner du temps.",
    4200,
    [
      ch("a", "Audit cadré et sobre", "safe", E({ flowDelta: 1600, balanceDelta: 800, transactionsDelta: 6, confidenceDelta: 10, momentumDelta: 2 })),
      ch("b", "Audit + feuille de route", "premium", E({ flowDelta: 3400, balanceDelta: 1100, transactionsDelta: 7, confidenceDelta: 4, riskDelta: 8, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Trop ambitieux, refuser", "refuse", E({ confidenceDelta: 3, momentumDelta: -2 })),
    ],
  ),
  sc(
    "commerce",
    "Package",
    "rare",
    "Créateur en précommande",
    "Un créateur veut une page de précommande pour valider son idée.",
    2400,
    [
      ch("a", "Page précommande nette", "safe", E({ flowDelta: 1300, balanceDelta: 550, transactionsDelta: 9, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Précommande + paliers", "premium", E({ flowDelta: 2700, balanceDelta: 800, transactionsDelta: 12, confidenceDelta: 3, riskDelta: 6, momentumDelta: 2 })),
      ch("c", "Attendre plus de preuves", "refuse", E({ confidenceDelta: 2, momentumDelta: -2 })),
    ],
  ),
  sc(
    "marketing",
    "MapPin",
    "common",
    "Artisan local",
    "Un artisan veut optimiser sa fiche Google et capter plus d'appels.",
    900,
    [
      ch("a", "Fiche optimisée", "safe", E({ flowDelta: 700, balanceDelta: 300, transactionsDelta: 6, confidenceDelta: 9, riskDelta: -1, momentumDelta: 1 })),
      ch("b", "Fiche + avis + photos", "premium", E({ flowDelta: 1400, balanceDelta: 450, transactionsDelta: 8, confidenceDelta: 6, riskDelta: 3, momentumDelta: 2 })),
      ch("c", "Refuser, ticket trop bas", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "cashflow",
    "Clock",
    "rare",
    "Client qui temporise",
    "Un client veut payer plus tard mais signer aujourd'hui.",
    3000,
    [
      ch("a", "Acompte 30 % à la signature", "safe", E({ flowDelta: 1500, balanceDelta: 900, transactionsDelta: 5, confidenceDelta: 9, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Échéancier clair en 3 fois", "premium", E({ flowDelta: 2600, balanceDelta: 700, transactionsDelta: 6, confidenceDelta: 5, riskDelta: 4, momentumDelta: 2 })),
      ch("c", "Pas de paiement, pas de start", "refuse", E({ confidenceDelta: 4, momentumDelta: -3 })),
    ],
  ),
  sc(
    "premium",
    "Crown",
    "epic",
    "Prospect premium hésitant",
    "Un prospect haut de gamme hésite sur une offre à forte valeur.",
    5000,
    [
      ch("a", "Rassurer avec une démo", "safe", E({ flowDelta: 1800, balanceDelta: 900, transactionsDelta: 5, confidenceDelta: 11, momentumDelta: 2 })),
      ch("b", "Offre signature premium", "premium", E({ flowDelta: 3600, balanceDelta: 1300, transactionsDelta: 6, confidenceDelta: 3, riskDelta: 9, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Laisser filer", "refuse", E({ momentumDelta: -3 })),
    ],
  ),
  sc(
    "risque",
    "Zap",
    "epic",
    "Opportunité urgente",
    "Une opportunité très rentable arrive, mais le périmètre est flou.",
    6000,
    [
      ch("a", "Cadrer avant de s'engager", "safe", E({ flowDelta: 1500, balanceDelta: 700, transactionsDelta: 5, confidenceDelta: 10, riskDelta: -1, momentumDelta: 2 })),
      ch("b", "Foncer pour le volume", "premium", E({ flowDelta: 4200, balanceDelta: 1100, transactionsDelta: 7, confidenceDelta: -2, riskDelta: 16, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Trop flou, refuser", "refuse", E({ confidenceDelta: 5, momentumDelta: -2 })),
    ],
  ),
  sc(
    "partenariat",
    "Handshake",
    "rare",
    "Partenaire à la commission",
    "Un partenaire propose d'apporter des clients contre une commission.",
    2600,
    [
      ch("a", "Commission raisonnable", "safe", E({ flowDelta: 1400, balanceDelta: 600, transactionsDelta: 8, confidenceDelta: 7, momentumDelta: 2 })),
      ch("b", "Volume contre marge réduite", "premium", E({ flowDelta: 2900, balanceDelta: 600, transactionsDelta: 12, confidenceDelta: 3, riskDelta: 7, momentumDelta: 2 })),
      ch("c", "Garder ses marges", "refuse", E({ confidenceDelta: 3, momentumDelta: -2 })),
    ],
  ),
  sc(
    "negociation",
    "Percent",
    "common",
    "Demande de réduction",
    "Un client veut une réduction importante avant de signer.",
    2000,
    [
      ch("a", "Réduire un peu, garder la valeur", "safe", E({ flowDelta: 1000, balanceDelta: 500, transactionsDelta: 6, confidenceDelta: 8, momentumDelta: 1 })),
      ch("b", "Échanger remise contre volume", "premium", E({ flowDelta: 2200, balanceDelta: 600, transactionsDelta: 10, confidenceDelta: 4, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Tenir son prix", "refuse", E({ confidenceDelta: 5, momentumDelta: -2 })),
    ],
  ),
  sc(
    "reputation",
    "RefreshCw",
    "rare",
    "Ancien client revient",
    "Un ancien client satisfait revient avec un nouveau besoin.",
    2300,
    [
      ch("a", "Reprendre la relation", "safe", E({ flowDelta: 1400, balanceDelta: 650, transactionsDelta: 7, confidenceDelta: 11, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Proposer un palier au-dessus", "premium", E({ flowDelta: 2500, balanceDelta: 800, transactionsDelta: 8, confidenceDelta: 6, riskDelta: 3, momentumDelta: 3 })),
      ch("c", "Pas de place pour lui", "refuse", E({ momentumDelta: -3 })),
    ],
  ),
  sc(
    "reputation",
    "Sparkles",
    "epic",
    "Recommandation inattendue",
    "Un contact influent te recommande publiquement à son réseau.",
    3200,
    [
      ch("a", "Répondre vite et bien", "safe", E({ flowDelta: 1700, balanceDelta: 700, transactionsDelta: 9, confidenceDelta: 13, riskDelta: -3, momentumDelta: 3 })),
      ch("b", "Capitaliser avec une offre", "premium", E({ flowDelta: 3100, balanceDelta: 900, transactionsDelta: 10, confidenceDelta: 7, riskDelta: 4, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Laisser passer", "refuse", E({ momentumDelta: -3 })),
    ],
  ),
  sc(
    "commerce",
    "ShoppingCart",
    "common",
    "Offre groupée",
    "Plusieurs petits clients pourraient être servis par une offre groupée.",
    1800,
    [
      ch("a", "Pack standard", "safe", E({ flowDelta: 1100, balanceDelta: 450, transactionsDelta: 10, confidenceDelta: 7, momentumDelta: 2 })),
      ch("b", "Pack groupé optimisé", "premium", E({ flowDelta: 2300, balanceDelta: 650, transactionsDelta: 14, confidenceDelta: 3, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Trop de logistique", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "urgence",
    "Bug",
    "rare",
    "Bug client critique",
    "Un client en production a un bug bloquant à résoudre vite.",
    1400,
    [
      ch("a", "Corriger en priorité", "safe", E({ flowDelta: 900, balanceDelta: 500, transactionsDelta: 4, confidenceDelta: 12, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Correctif + contrat de suivi", "premium", E({ flowDelta: 2000, balanceDelta: 700, transactionsDelta: 6, confidenceDelta: 7, riskDelta: 3, momentumDelta: 2 })),
      ch("c", "Reporter à demain", "refuse", E({ confidenceDelta: -3, momentumDelta: -3 })),
    ],
  ),
  sc(
    "risque",
    "HelpCircle",
    "rare",
    "Mission express floue",
    "Une mission urgente est bien payée mais mal définie.",
    3400,
    [
      ch("a", "Exiger un brief écrit", "safe", E({ flowDelta: 1300, balanceDelta: 600, transactionsDelta: 5, confidenceDelta: 10, riskDelta: -1, momentumDelta: 1 })),
      ch("b", "Démarrer avec une réserve", "premium", E({ flowDelta: 2800, balanceDelta: 800, transactionsDelta: 6, confidenceDelta: 1, riskDelta: 11, momentumDelta: 2 })),
      ch("c", "Refuser sans cadrage", "refuse", E({ confidenceDelta: 4, momentumDelta: -2 })),
    ],
  ),
  sc(
    "premium",
    "Gift",
    "epic",
    "Pack premium à proposer",
    "Un bon client est prêt à monter en gamme si tu proposes le bon pack.",
    4800,
    [
      ch("a", "Pack confort équilibré", "safe", E({ flowDelta: 1900, balanceDelta: 900, transactionsDelta: 6, confidenceDelta: 10, momentumDelta: 2 })),
      ch("b", "Pack signature haut de gamme", "premium", E({ flowDelta: 3500, balanceDelta: 1200, transactionsDelta: 7, confidenceDelta: 4, riskDelta: 8, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Rester sur l'offre actuelle", "refuse", E({ confidenceDelta: 2, momentumDelta: -2 })),
    ],
  ),
  sc(
    "negociation",
    "TrendingUp",
    "common",
    "Vente additionnelle",
    "Un client satisfait pourrait acheter un service complémentaire.",
    1600,
    [
      ch("a", "Proposer simplement", "safe", E({ flowDelta: 1000, balanceDelta: 450, transactionsDelta: 7, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Bundle complémentaire", "premium", E({ flowDelta: 2100, balanceDelta: 650, transactionsDelta: 9, confidenceDelta: 4, riskDelta: 4, momentumDelta: 2 })),
      ch("c", "Ne rien proposer", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "freelance",
    "Timer",
    "common",
    "Micro-service express",
    "Un micro-service peut être livré en 2h pour un besoin immédiat.",
    600,
    [
      ch("a", "Livrer le micro-service", "safe", E({ flowDelta: 600, balanceDelta: 350, transactionsDelta: 9, confidenceDelta: 6, momentumDelta: 2 })),
      ch("b", "Micro-service + option", "premium", E({ flowDelta: 1200, balanceDelta: 450, transactionsDelta: 12, confidenceDelta: 3, riskDelta: 3, momentumDelta: 2 })),
      ch("c", "Trop petit", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "cashflow",
    "Repeat",
    "epic",
    "Contrat récurrent",
    "Un client propose un abonnement mensuel stable et prévisible.",
    3000,
    [
      ch("a", "Abonnement simple", "safe", E({ flowDelta: 1700, balanceDelta: 1000, transactionsDelta: 6, confidenceDelta: 12, riskDelta: -3, momentumDelta: 2 })),
      ch("b", "Abonnement + engagement 6 mois", "premium", E({ flowDelta: 3000, balanceDelta: 1200, transactionsDelta: 7, confidenceDelta: 7, riskDelta: 2, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Préférer le ponctuel", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "risque",
    "Edit",
    "rare",
    "Client jamais content",
    "Un client demande sans cesse des modifications hors périmètre.",
    2100,
    [
      ch("a", "Recadrer le périmètre", "safe", E({ flowDelta: 900, balanceDelta: 500, transactionsDelta: 4, confidenceDelta: 9, riskDelta: -2, momentumDelta: 1 })),
      ch("b", "Facturer les extras", "premium", E({ flowDelta: 2000, balanceDelta: 700, transactionsDelta: 6, confidenceDelta: 3, riskDelta: 6, momentumDelta: 2 })),
      ch("c", "Tout accepter pour finir", "refuse", E({ confidenceDelta: -4, riskDelta: 8, momentumDelta: -1 })),
    ],
  ),
  sc(
    "negociation",
    "FileText",
    "common",
    "Offre claire vs floue",
    "Tu peux envoyer une offre claire et cadrée, ou une offre vague plus large.",
    2500,
    [
      ch("a", "Offre claire et cadrée", "safe", E({ flowDelta: 1300, balanceDelta: 650, transactionsDelta: 6, confidenceDelta: 11, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Offre large mais floue", "premium", E({ flowDelta: 2600, balanceDelta: 700, transactionsDelta: 7, confidenceDelta: -1, riskDelta: 9, momentumDelta: 2 })),
      ch("c", "Demander un cadrage payant", "refuse", E({ confidenceDelta: 5, momentumDelta: -2 })),
    ],
  ),
  sc(
    "cashflow",
    "Wallet",
    "rare",
    "Acompte ou solde final",
    "Le client te laisse choisir : gros acompte maintenant ou tout à la fin.",
    3200,
    [
      ch("a", "Gros acompte maintenant", "safe", E({ flowDelta: 1500, balanceDelta: 1100, transactionsDelta: 5, confidenceDelta: 9, riskDelta: -3, momentumDelta: 2 })),
      ch("b", "Tout à la fin, montant majoré", "premium", E({ flowDelta: 3000, balanceDelta: 300, transactionsDelta: 6, confidenceDelta: 2, riskDelta: 10, momentumDelta: 2 })),
      ch("c", "Refuser sans acompte", "refuse", E({ confidenceDelta: 4, momentumDelta: -2 })),
    ],
  ),
  sc(
    "premium",
    "Building2",
    "epic",
    "Client corporate",
    "Une entreprise veut une démo avant un contrat potentiellement important.",
    7000,
    [
      ch("a", "Démo carrée et sobre", "safe", E({ flowDelta: 2000, balanceDelta: 900, transactionsDelta: 5, confidenceDelta: 12, momentumDelta: 2 })),
      ch("b", "Démo + proposition cadrée", "premium", E({ flowDelta: 3800, balanceDelta: 1300, transactionsDelta: 6, confidenceDelta: 5, riskDelta: 7, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Pas le temps pour une démo", "refuse", E({ confidenceDelta: -2, momentumDelta: -3 })),
    ],
  ),
  sc(
    "commerce",
    "Store",
    "common",
    "Boutique simple",
    "Un créateur veut une petite boutique en ligne pour vendre 3 produits.",
    2000,
    [
      ch("a", "Boutique minimaliste", "safe", E({ flowDelta: 1200, balanceDelta: 500, transactionsDelta: 9, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Boutique + upsell", "premium", E({ flowDelta: 2400, balanceDelta: 700, transactionsDelta: 12, confidenceDelta: 4, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Refuser", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "commerce",
    "QrCode",
    "common",
    "QR menu + avis",
    "Un restaurant veut un menu en QR code et collecter des avis clients.",
    1300,
    [
      ch("a", "Menu QR propre", "safe", E({ flowDelta: 800, balanceDelta: 400, transactionsDelta: 8, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "QR menu + collecte d'avis", "premium", E({ flowDelta: 1700, balanceDelta: 550, transactionsDelta: 11, confidenceDelta: 5, riskDelta: 4, momentumDelta: 2 })),
      ch("c", "Pas pour toi", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "marketing",
    "Wrench",
    "common",
    "Plombier débordé",
    "Un plombier veut plus d'appels entrants sans perdre de temps.",
    1100,
    [
      ch("a", "Page locale + clic-to-call", "safe", E({ flowDelta: 800, balanceDelta: 400, transactionsDelta: 7, confidenceDelta: 9, riskDelta: -1, momentumDelta: 2 })),
      ch("b", "Page + campagne ciblée", "premium", E({ flowDelta: 1700, balanceDelta: 550, transactionsDelta: 9, confidenceDelta: 4, riskDelta: 5, momentumDelta: 2 })),
      ch("c", "Refuser", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "premium",
    "Camera",
    "rare",
    "Photographe ambitieux",
    "Un photographe veut un portfolio premium qui justifie des tarifs plus hauts.",
    2700,
    [
      ch("a", "Portfolio élégant", "safe", E({ flowDelta: 1400, balanceDelta: 650, transactionsDelta: 6, confidenceDelta: 10, momentumDelta: 2 })),
      ch("b", "Portfolio + page de réservation", "premium", E({ flowDelta: 2700, balanceDelta: 850, transactionsDelta: 8, confidenceDelta: 5, riskDelta: 6, momentumDelta: 2 })),
      ch("c", "Décliner", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "commerce",
    "Ticket",
    "rare",
    "Billetterie d'événement",
    "Un événement local a besoin d'une billetterie en ligne rapidement.",
    3300,
    [
      ch("a", "Billetterie simple", "safe", E({ flowDelta: 1500, balanceDelta: 700, transactionsDelta: 12, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Billetterie + places VIP", "premium", E({ flowDelta: 3000, balanceDelta: 900, transactionsDelta: 16, confidenceDelta: 3, riskDelta: 6, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Délai trop serré", "refuse", E({ confidenceDelta: 2, momentumDelta: -2 })),
    ],
  ),
  sc(
    "marketing",
    "Megaphone",
    "rare",
    "Page sponsor influenceur",
    "Un créateur de contenu veut une page pour ses partenariats sponsorisés.",
    2900,
    [
      ch("a", "Page média soignée", "safe", E({ flowDelta: 1500, balanceDelta: 650, transactionsDelta: 7, confidenceDelta: 9, momentumDelta: 2 })),
      ch("b", "Page + kit de vente", "premium", E({ flowDelta: 2900, balanceDelta: 800, transactionsDelta: 9, confidenceDelta: 4, riskDelta: 6, momentumDelta: 3 })),
      ch("c", "Refuser", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "partenariat",
    "Network",
    "epic",
    "Agence qui sous-traite",
    "Une agence veut te confier une partie de ses projets en marque blanche.",
    5500,
    [
      ch("a", "Volume raisonnable", "safe", E({ flowDelta: 2000, balanceDelta: 900, transactionsDelta: 10, confidenceDelta: 9, momentumDelta: 2 })),
      ch("b", "Gros volume, deadlines serrées", "premium", E({ flowDelta: 3900, balanceDelta: 1000, transactionsDelta: 16, confidenceDelta: 2, riskDelta: 12, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Protéger sa capacité", "refuse", E({ confidenceDelta: 4, momentumDelta: -2 })),
    ],
  ),
  sc(
    "risque",
    "AlertTriangle",
    "legendary",
    "Projet trop beau",
    "Un projet promet un gros chiffre, mais le client met une pression énorme.",
    9000,
    [
      ch("a", "Cadrer durement avant d'accepter", "safe", E({ flowDelta: 2200, balanceDelta: 1000, transactionsDelta: 6, confidenceDelta: 12, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Tout miser dessus", "premium", E({ flowDelta: 5200, balanceDelta: 1400, transactionsDelta: 8, confidenceDelta: -3, riskDelta: 20, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Refuser la pression", "refuse", E({ confidenceDelta: 6, momentumDelta: -2 })),
    ],
  ),
  sc(
    "ia",
    "ClipboardCheck",
    "rare",
    "Audit express rentable",
    "Une boutique veut un audit rapide de son tunnel de vente.",
    2600,
    [
      ch("a", "Audit ciblé", "safe", E({ flowDelta: 1400, balanceDelta: 700, transactionsDelta: 5, confidenceDelta: 10, momentumDelta: 2 })),
      ch("b", "Audit + plan d'action chiffré", "premium", E({ flowDelta: 2700, balanceDelta: 900, transactionsDelta: 7, confidenceDelta: 5, riskDelta: 5, momentumDelta: 3 })),
      ch("c", "Pas le temps", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "cashflow",
    "Settings",
    "epic",
    "Maintenance mensuelle",
    "Après un projet, tu peux proposer une maintenance récurrente.",
    2400,
    [
      ch("a", "Forfait maintenance léger", "safe", E({ flowDelta: 1500, balanceDelta: 900, transactionsDelta: 6, confidenceDelta: 11, riskDelta: -3, momentumDelta: 2 })),
      ch("b", "Forfait + monitoring premium", "premium", E({ flowDelta: 2800, balanceDelta: 1100, transactionsDelta: 8, confidenceDelta: 6, riskDelta: 2, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Ne pas proposer", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "premium",
    "Rocket",
    "legendary",
    "Offre « done for you »",
    "Un client veut une solution clé en main, livrée et pilotée de A à Z.",
    8000,
    [
      ch("a", "Done for you cadré", "safe", E({ flowDelta: 2400, balanceDelta: 1200, transactionsDelta: 7, confidenceDelta: 12, momentumDelta: 2 })),
      ch("b", "Done for you premium + suivi", "premium", E({ flowDelta: 4600, balanceDelta: 1500, transactionsDelta: 9, confidenceDelta: 6, riskDelta: 9, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Trop d'engagement", "refuse", E({ confidenceDelta: 2, momentumDelta: -3 })),
    ],
  ),
  sc(
    "ia",
    "Bot",
    "rare",
    "Pack automatique basse charge",
    "Un client veut un système qui tourne seul avec peu d'intervention.",
    2200,
    [
      ch("a", "Automatisation simple", "safe", E({ flowDelta: 1300, balanceDelta: 700, transactionsDelta: 8, confidenceDelta: 9, riskDelta: -1, momentumDelta: 2 })),
      ch("b", "Automatisation + tableau de bord", "premium", E({ flowDelta: 2500, balanceDelta: 900, transactionsDelta: 10, confidenceDelta: 5, riskDelta: 5, momentumDelta: 3 })),
      ch("c", "Décliner", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "freelance",
    "PenTool",
    "common",
    "Identité de marque",
    "Un jeune entrepreneur veut une identité visuelle simple pour se lancer.",
    1500,
    [
      ch("a", "Kit identité essentiel", "safe", E({ flowDelta: 1000, balanceDelta: 500, transactionsDelta: 6, confidenceDelta: 8, momentumDelta: 2 })),
      ch("b", "Identité + déclinaisons", "premium", E({ flowDelta: 2000, balanceDelta: 650, transactionsDelta: 8, confidenceDelta: 4, riskDelta: 4, momentumDelta: 2 })),
      ch("c", "Trop tôt pour lui", "refuse", E({ confidenceDelta: 2, momentumDelta: -2 })),
    ],
  ),
  sc(
    "reputation",
    "Star",
    "rare",
    "Étude de cas publique",
    "Un client accepte de devenir une étude de cas mise en avant.",
    1800,
    [
      ch("a", "Étude de cas soignée", "safe", E({ flowDelta: 1100, balanceDelta: 500, transactionsDelta: 6, confidenceDelta: 13, riskDelta: -3, momentumDelta: 3 })),
      ch("b", "Étude de cas + offre dérivée", "premium", E({ flowDelta: 2100, balanceDelta: 700, transactionsDelta: 8, confidenceDelta: 8, riskDelta: 2, momentumDelta: 3 })),
      ch("c", "Garder ça privé", "refuse", E({ momentumDelta: -2 })),
    ],
  ),
  sc(
    "negociation",
    "Scale",
    "rare",
    "Deux clients, un créneau",
    "Deux clients veulent le même créneau : un sûr et modeste, un gros mais pressant.",
    4000,
    [
      ch("a", "Le client sûr et calme", "safe", E({ flowDelta: 1600, balanceDelta: 800, transactionsDelta: 7, confidenceDelta: 11, riskDelta: -2, momentumDelta: 2 })),
      ch("b", "Le gros client pressant", "premium", E({ flowDelta: 3300, balanceDelta: 1000, transactionsDelta: 8, confidenceDelta: 2, riskDelta: 11, momentumDelta: 3, multiplierDelta: 1 })),
      ch("c", "Repousser les deux", "refuse", E({ confidenceDelta: 3, momentumDelta: -3 })),
    ],
  ),
];

if (SCENARIOS.length < 40) {
  // Safety net during development — should never trigger in production.
  throw new Error(`Scenario bank too small: ${SCENARIOS.length}`);
}
